ya_news/news/urls.py
from django.urls import path

from news import views

app_name = 'news'

urlpatterns = [
    path('', views.NewsList.as_view(), name='home'),
    path('news/<int:pk>/', views.NewsDetailView.as_view(), name='detail'),
    path(
        'delete_comment/<int:pk>/',
        views.CommentDelete.as_view(),
        name='delete'
    ),
    path('edit_comment/<int:pk>/', views.CommentUpdate.as_view(), name='edit'),
]

ya_news/yanews/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm
from django.urls import include, path
from django.views.generic import CreateView

urlpatterns = [
    path('', include('news.urls')),
    path('admin/', admin.site.urls),
]

auth_urls = ([
    path(
        'login/',
        auth_views.LoginView.as_view(),
        name='login',
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name='registration/logout.html'
        ),
        name='logout',
    ),
    path(
        'signup/',
        CreateView.as_view(
            form_class=UserCreationForm,
            success_url='/',
            template_name='registration/signup.html',
        ),
        name='signup'
    ),
], 'users')

urlpatterns += [path('auth/', include(auth_urls))]

ya_news/news/models.py
from datetime import datetime

from django.conf import settings
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()
    date = models.DateField(default=datetime.today)

    class Meta:
        ordering = ('-date',)
        verbose_name_plural = 'Новости'
        verbose_name = 'Новость'

    def __str__(self):
        return self.title


class Comment(models.Model):
    news = models.ForeignKey(
        News,
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.text[:50]

ya_news/news/forms.py
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from .models import Comment

BAD_WORDS = (
    'редиска',
    'негодяй',
    # Дополните список на своё усмотрение.
)
WARNING = 'Не ругайтесь!'


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

    def clean_text(self):
        """Не позволяем ругаться в комментариях."""
        text = self.cleaned_data['text']
        lowered_text = text.lower()
        for word in BAD_WORDS:
            if word in lowered_text:
                raise ValidationError(WARNING)
        return text

ya_news/news/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from .forms import CommentForm
from .models import Comment, News


class NewsList(generic.ListView):
    """Список новостей."""
    model = News
    template_name = 'news/home.html'

    def get_queryset(self):
        """
        Выводим только несколько последних новостей.

        Их количество определяется в настройках проекта.
        """
        return self.model.objects.prefetch_related(
            'comment_set'
        )[:settings.NEWS_COUNT_ON_HOME_PAGE]


class NewsDetail(generic.DetailView):
    model = News
    template_name = 'news/detail.html'

    def get_object(self, queryset=None):
        obj = get_object_or_404(
            self.model.objects.prefetch_related('comment_set__author'),
            pk=self.kwargs['pk']
        )
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['form'] = CommentForm()
        return context


class NewsComment(
        LoginRequiredMixin,
        generic.detail.SingleObjectMixin,
        generic.FormView
):
    model = News
    form_class = CommentForm
    template_name = 'news/detail.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.news = self.object
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        post = self.get_object()
        return reverse('news:detail', kwargs={'pk': post.pk}) + '#comments'


class NewsDetailView(generic.View):

    def get(self, request, *args, **kwargs):
        view = NewsDetail.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = NewsComment.as_view()
        return view(request, *args, **kwargs)


class CommentBase(LoginRequiredMixin):
    """Базовый класс для работы с комментариями."""
    model = Comment

    def get_success_url(self):
        comment = self.get_object()
        return reverse(
            'news:detail', kwargs={'pk': comment.news.pk}
        ) + '#comments'

    def get_queryset(self):
        """Пользователь может работать только со своими комментариями."""
        return self.model.objects.filter(author=self.request.user)


class CommentUpdate(CommentBase, generic.UpdateView):
    """Редактирование комментария."""
    template_name = 'news/edit.html'
    form_class = CommentForm


class CommentDelete(CommentBase, generic.DeleteView):
    """Удаление комментария."""
    template_name = 'news/delete.html'

ya_news/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous">
  </head>
  <body class="bg-light">
    {% include "includes/header.html" %}
    <div class="container mt-3">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

ya_news/templates/includes/errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

ya_news/templates/includes/header.html
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <li class="container">
      <a class="navbar-brand" href="{% url 'news:home' %}">
        <span class="text-danger"><b>Ya</b></span>News
      </a>
      <ul class="nav nav-pills">
        {% if user.is_authenticated %}
          <li class="align-self-center">
            Пользователь: {{ user.username }}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    </li>
  </nav>
</header>

ya_news/templates/news/delete.html
{% extends "base.html" %}
{% block content %}
  <h2>Удалить комментарий к новости?</h2>
  <h3>{{ comment.news.title }}</h3>
  <hr>
  <p>{{ comment.created }}</p>
  <p>{{ comment.text }}</p>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    <div class="form-actions">
      <button type="submit" class="btn btn-primary" >Удалить</button>
    </div>
  </form>
{% endblock content %}

ya_news/templates/news/detail.html
{% extends "base.html" %}
{% block content %}
  <a href="{% url 'news:home' %}">На главную</a>
  <hr>
  <h2>{{ news.title }}</h2>
  <p>{{ news.text }}</p>
  <p>{{ news.date }}</p>
  <hr>
  <h3 id="comments">Комментарии:</h3>
  {% for comment in news.comment_set.all %}
    <div>
      <b>{{ comment.author }}</b>, {{ comment.created }}</b>
      <p class="mb-0">{{ comment.text|linebreaksbr }}</p>
      {% if comment.author == user %}
        <a href="{% url 'news:edit' comment.pk %}">Редактировать</a> |
        <a href="{% url 'news:delete' comment.pk %}">Удалить</a>
      {% endif %}
    </div>
    <br>
  {% empty %}
    <p>Здесь никто ничего не написал...</p>
  {% endfor %}
  {% if user.is_authenticated %}
    <hr>
    <div class="col-md-3">
      <h3>Оставить комментарий:</h3>
      <form action="" method="post">
        {% csrf_token %}
        {% include "includes/errors.html" %}
        {% for field in form %}
          {{ field }}
        {% endfor %}
        <div class="form-actions">
          <button type="submit" class="btn btn-primary" >Сохранить</button>
        </div>
      </form>
    </div>
  {% endif %}
{% endblock content %}

ya_news/templates/news/edit.html
{% extends "base.html" %}
{% block content %}
  <h2>Редактировать комментарий к новости</h2>
  <h3>{{ comment.news.title }}</h3>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {% include "includes/errors.html" %}
    {% for field in form %}
      {{ field }}
    {% endfor %}
    <div class="form-actions">
      <button type="submit" class="btn btn-primary" >Сохранить</button>
    </div>
  </form>
{% endblock %}

ya_news/templates/news/home.html
{% extends "base.html" %}
{% block content %}
  {% for news in object_list %}
    <div class="mt-3">
      <h3><a href="{% url 'news:detail' news.pk %}">{{ news.title }}</a></h3>
      <div><small>{{ news.date }}</small></div>
      <div>{{ news.text|truncatewords:15 }}</div>
      {% if news.comment_set.all %}
        <ul>
          <li>
            Комментариев: {{ news.comment_set.count }}
          </li>
        </ul>
      {% endif %}
    </div>
  {% endfor %}
{% endblock content %}