ya_note/notes/urls.py
from django.urls import path

from notes import views

app_name = 'notes'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('add/', views.NoteCreate.as_view(), name='add'),
    path('edit/<slug:slug>/', views.NoteUpdate.as_view(), name='edit'),
    path('note/<slug:slug>/', views.NoteDetail.as_view(), name='detail'),
    path('delete/<slug:slug>/', views.NoteDelete.as_view(), name='delete'),
    path('notes/', views.NotesList.as_view(), name='list'),
    path('done/', views.NoteSuccess.as_view(), name='success'),
]

ya_note/yanote/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm
from django.urls import include, path
from django.views.generic import CreateView

urlpatterns = [
    path('', include('notes.urls')),
    path('admin/', admin.site.urls),
]

auth_urls = ([
    path(
        'login/',
        auth_views.LoginView.as_view(),
        name='login',
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name='registration/logout.html'
        ),
        name='logout',
    ),
    path(
        'signup/',
        CreateView.as_view(
            form_class=UserCreationForm,
            success_url='/',
            template_name='registration/signup.html',
        ),
        name='signup'
    ),
], 'users')

urlpatterns += [path('auth/', include(auth_urls))]

ya_note/notes/models.py
from django.conf import settings
from django.db import models

from pytils.translit import slugify


class Note(models.Model):
    title = models.CharField(
        'Заголовок',
        max_length=100,
        default='Название заметки',
        help_text='Дайте короткое название заметке'
    )
    text = models.TextField(
        'Текст',
        help_text='Добавьте подробностей'
    )
    slug = models.SlugField(
        'Адрес для страницы с заметкой',
        max_length=100,
        unique=True,
        blank=True,
        help_text=('Укажите адрес для страницы заметки. Используйте только '
                   'латиницу, цифры, дефисы и знаки подчёркивания')
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            max_slug_length = self._meta.get_field('slug').max_length
            self.slug = slugify(self.title)[:max_slug_length]
        super().save(*args, **kwargs)

ya_note/notes/forms.py
from pytils.translit import slugify

from django import forms
from django.core.exceptions import ValidationError

from .models import Note

WARNING = ' - такой slug уже существует, придумайте уникальное значение!'


class NoteForm(forms.ModelForm):
    """Форма для создания или обновления заметки."""

    class Meta:
        model = Note
        fields = ('title', 'text', 'slug')

    def clean_slug(self):
        """Обрабатывает случай, если slug не уникален."""
        cleaned_data = super().clean()
        slug = cleaned_data.get('slug')
        if not slug:
            title = cleaned_data.get('title')
            slug = slugify(title)[:100]
        if Note.objects.filter(
                slug=slug
        ).exclude(id=self.instance.pk).exists():
            raise ValidationError(slug + WARNING)
        return slug

ya_note/notes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from .forms import NoteForm
from .models import Note


class Home(generic.TemplateView):
    """Домашняя страница."""
    template_name = 'notes/home.html'


class NoteSuccess(LoginRequiredMixin, generic.TemplateView):
    """Страница успешного выполнения операции."""
    template_name = 'notes/success.html'


class NoteBase(LoginRequiredMixin):
    """Базовый класс для остальных CBV."""
    model = Note
    success_url = reverse_lazy('notes:success')

    def get_queryset(self):
        """Пользователь может работать только со своими заметками."""
        return self.model.objects.filter(author=self.request.user)


class NoteCreate(NoteBase, generic.CreateView):
    """Добавление заметки."""
    template_name = 'notes/form.html'
    form_class = NoteForm

    def form_valid(self, form):
        new_note = form.save(commit=False)
        new_note.author = self.request.user
        new_note.save()
        return super().form_valid(form)


class NoteUpdate(NoteBase, generic.UpdateView):
    """Редактирование заметки."""
    template_name = 'notes/form.html'
    form_class = NoteForm


class NoteDelete(NoteBase, generic.DeleteView):
    """Удаление заметки."""
    template_name = 'notes/delete.html'


class NotesList(NoteBase, generic.ListView):
    """Список всех заметок пользователя."""
    template_name = 'notes/list.html'


class NoteDetail(NoteBase, generic.DetailView):
    """Заметка подробно."""
    template_name = 'notes/detail.html'

ya_note/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous">
  </head>
  <body class="bg-light">
    {% include "includes/header.html" %}
    <div class="container mt-3">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

ya_note/templates/includes/errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

ya_note/templates/includes/header.html
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'notes:home' %}">
        <span class="text-danger"><b>Ya</b></span>Note
      </a>
      {% if user.is_authenticated %}
          <div class="nav-item align-self-center mt-1">
            пользователя {{ user.username }}
          </div>
        <div class="spacer flex-grow-1"></div>
      {% endif %}
      <ul class="nav nav-pills">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'notes:list' %}">Список заметок</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'notes:add' %}">Новая заметка</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>

ya_note/templates/notes/delete.html
{% extends "base.html" %}
{% block content %}
  <h2>Удалить заметку {{ note.id }}?</h2>
  <hr>
  <h3>{{ note.title }}</h3>
  <p>{{ note.text }}</p>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    <div class="form-actions">
      <button type="submit" class="btn btn-primary" >Удалить</button>
    </div>
  </form>
{% endblock content %}

ya_note/templates/notes/detail.html
{% extends "base.html" %}
{% block content %}
  <h2>Заметка ID: {{ note.id }}</h2>
  <hr>
  <h3>{{ note.title }}</h3>
  <p>{{ note.text }}</p>
  <hr>
  <p>
    <a href="{% url 'notes:edit' slug=note.slug %}">Редактировать</a>
  </p>
  <p>
    <a href="{% url 'notes:delete' slug=note.slug %}">Удалить</a>
  </p>
{% endblock content %}

ya_note/templates/notes/form.html
{% extends "base.html" %}
{% block content %}
  <h2>
    {% if request.path == '/add/' %}
      Добавить
    {% else %}
      Редактировать
    {% endif %}
    заметку
  </h2>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    {% include "includes/errors.html" %}
    <fieldset>
      <legend>{{ title }}</legend>
      {% for field in form %}
        <div class="control-group">
          <label class="control-label">{{ field.label }}</label>
          <div class="controls">
            {{ field }}
            {% if field.help_text %}
              <p class="help-inline"><small>{{ field.help_text }}</small></p>
            {% endif %}
          </div>
        </div>
      {% endfor %}
    </fieldset>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary" >Сохранить</button>
    </div>
  </form>
{% endblock %}

ya_note/templates/notes/home.html
{% extends "base.html" %}
{% block content %}
  <h2>О проекте</h2>
  <p>
    Проект YaNote поможет вам не забыть о самом важном!
  </p>
{% endblock content %}

ya_note/templates/notes/list.html
{% extends "base.html" %}
{% block content %}
  <h2>Список заметок</h2>
  <ul>
    {% for note in object_list %}
      <li>
        {{ note.id }}:
        <a href="{% url 'notes:detail' note.slug %}"> {{ note.title }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

ya_note/templates/notes/success.html
{% extends "base.html" %}
{% block content %}
  <h2>Успешно</h2>
  <ul>
    <li>
      <a href="{% url 'notes:home' %}">На главную</a>
    </li>
    <li>
      <a href="{% url 'notes:list' %}">К списку заметок</a>
    </li>
  </ul>
{% endblock content %}